"""A/B Testing via Shadow (Paper) Trading of candidate models.

Never deploy a new model to live without shadow testing. This module:
- Runs candidate models in parallel without real execution
- Tracks simulated P&L as if trades were executed
- Compares shadow vs live performance over N bars
- Supports gradual rollout (0% → 25% → 50% → 75% → 100%)
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

import numpy as np

from apexfx.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class ShadowSignal:
    """A signal generated by a shadow model on a single bar."""
    timestamp: str
    action: float           # Model's proposed action [-1, 1]
    actual_price: float     # Market price at signal time
    simulated_position: float  # Simulated position after action


@dataclass
class ShadowResult:
    """Simulated performance of a shadow model."""
    model_id: str
    n_signals: int
    simulated_pnl: float
    simulated_sharpe: float
    signal_correlation: float    # Correlation with live model actions
    action_divergence: float     # Mean |shadow_action - live_action|
    would_have_won: int          # Times shadow was better than live


class ShadowTrader:
    """Runs candidate models in parallel without execution.

    Every bar, the shadow model generates a signal. We track what would
    have happened if we'd followed it. After N bars, compare shadow vs
    live performance to decide on promotion.
    """

    def __init__(
        self,
        evaluation_bars: int = 500,
        promotion_threshold: float = 0.3,
    ) -> None:
        """Initialize shadow trader.

        Args:
            evaluation_bars: Number of bars to evaluate before comparing
            promotion_threshold: Shadow must beat live by this Sharpe delta
        """
        self._evaluation_bars = evaluation_bars
        self._promotion_threshold = promotion_threshold

        # Shadow model tracking
        self._shadow_signals: dict[str, list[ShadowSignal]] = {}
        self._shadow_positions: dict[str, float] = {}  # model_id → current position

        # Live model tracking for comparison
        self._live_actions: list[float] = []
        self._live_returns: list[float] = []

        # Price history
        self._prices: list[float] = []

    def register_shadow(self, model_id: str) -> None:
        """Register a new shadow model for tracking."""
        self._shadow_signals[model_id] = []
        self._shadow_positions[model_id] = 0.0
        logger.info("Shadow model registered", model_id=model_id)

    def on_bar(
        self,
        live_action: float,
        shadow_actions: dict[str, float],
        actual_price: float,
        live_return: float = 0.0,
    ) -> None:
        """Process a bar: record live and shadow signals.

        Args:
            live_action: The actual live model's action
            shadow_actions: {model_id: action} for each shadow model
            actual_price: Market price at this bar
            live_return: Actual return of the live system for this bar
        """
        now = datetime.now(UTC).isoformat()

        self._live_actions.append(live_action)
        self._live_returns.append(live_return)
        self._prices.append(actual_price)

        for model_id, action in shadow_actions.items():
            if model_id not in self._shadow_signals:
                self.register_shadow(model_id)

            # Simulate position change
            prev_pos = self._shadow_positions.get(model_id, 0.0)
            if abs(action) < 0.05:
                new_pos = 0.0
            else:
                new_pos = action  # Simplified: action IS the position

            self._shadow_positions[model_id] = new_pos

            signal = ShadowSignal(
                timestamp=now,
                action=action,
                actual_price=actual_price,
                simulated_position=new_pos,
            )
            self._shadow_signals[model_id].append(signal)

        # Trim to evaluation window
        if len(self._live_actions) > self._evaluation_bars * 2:
            self._live_actions = self._live_actions[-self._evaluation_bars:]
            self._live_returns = self._live_returns[-self._evaluation_bars:]
            self._prices = self._prices[-self._evaluation_bars:]
            for mid in self._shadow_signals:
                self._shadow_signals[mid] = self._shadow_signals[mid][-self._evaluation_bars:]

    def evaluate(self, model_id: str) -> ShadowResult | None:
        """Evaluate a shadow model against live performance.

        Returns None if insufficient data.
        """
        signals = self._shadow_signals.get(model_id, [])
        if len(signals) < 50:
            return None

        n = min(len(signals), len(self._prices) - 1, len(self._live_actions))
        if n < 50:
            return None

        # Compute simulated returns for shadow model
        shadow_returns = []
        for i in range(1, n):
            pos = signals[i - 1].simulated_position
            price_return = (self._prices[i] - self._prices[i - 1]) / (self._prices[i - 1] + 1e-10)
            shadow_returns.append(pos * price_return)

        shadow_arr = np.array(shadow_returns)
        live_arr = np.array(self._live_returns[1:n])

        # Sharpe ratios
        shadow_sharpe = self._compute_sharpe(shadow_arr)
        live_sharpe = self._compute_sharpe(live_arr)

        # Signal correlation
        shadow_actions = np.array([s.action for s in signals[:n]])
        live_actions_arr = np.array(self._live_actions[:n])
        if np.std(shadow_actions) > 0 and np.std(live_actions_arr) > 0:
            correlation = float(np.corrcoef(shadow_actions, live_actions_arr)[0, 1])
        else:
            correlation = 0.0

        # Action divergence
        divergence = float(np.mean(np.abs(shadow_actions - live_actions_arr)))

        # Count times shadow would have been better
        would_have_won = 0
        for i in range(len(shadow_returns)):
            if i < len(live_arr) and shadow_returns[i] > live_arr[i]:
                would_have_won += 1

        result = ShadowResult(
            model_id=model_id,
            n_signals=n,
            simulated_pnl=float(np.sum(shadow_arr)),
            simulated_sharpe=shadow_sharpe,
            signal_correlation=correlation,
            action_divergence=divergence,
            would_have_won=would_have_won,
        )

        logger.info(
            "Shadow evaluation",
            model_id=model_id,
            n_signals=n,
            shadow_sharpe=round(shadow_sharpe, 4),
            live_sharpe=round(live_sharpe, 4),
            correlation=round(correlation, 4),
        )

        return result

    def should_promote(self, model_id: str) -> bool:
        """Check if a shadow model should be promoted to live."""
        result = self.evaluate(model_id)
        if result is None:
            return False

        if result.n_signals < self._evaluation_bars:
            return False

        live_sharpe = self._compute_sharpe(np.array(self._live_returns[-result.n_signals:]))
        sharpe_delta = result.simulated_sharpe - live_sharpe

        if sharpe_delta >= self._promotion_threshold:
            logger.info(
                "Shadow model ready for promotion",
                model_id=model_id,
                sharpe_delta=round(sharpe_delta, 4),
                threshold=self._promotion_threshold,
            )
            return True

        return False

    def evaluate_all(self) -> list[ShadowResult]:
        """Evaluate all registered shadow models."""
        results = []
        for model_id in self._shadow_signals:
            result = self.evaluate(model_id)
            if result is not None:
                results.append(result)
        return results

    @staticmethod
    def _compute_sharpe(returns: np.ndarray, annualization: float = 252.0) -> float:
        """Compute annualized Sharpe ratio."""
        if len(returns) < 2:
            return 0.0
        std = np.std(returns, ddof=1)
        if std < 1e-10:
            return 0.0
        return float(np.mean(returns) / std * np.sqrt(annualization))


class GradualRollout:
    """Gradual promotion of shadow model to live.

    Instead of instant switch, gradually increases shadow model's
    weight in the final decision over configurable number of bars.
    """

    def __init__(self, ramp_bars: int = 200) -> None:
        """Initialize gradual rollout.

        Args:
            ramp_bars: Number of bars for 0% → 100% transition
        """
        self._ramp_bars = max(1, ramp_bars)
        self._current_bar = 0
        self._active = False

    def start(self) -> None:
        """Begin gradual rollout."""
        self._current_bar = 0
        self._active = True
        logger.info("Gradual rollout started", ramp_bars=self._ramp_bars)

    def stop(self) -> None:
        """Stop rollout (revert to live model)."""
        self._active = False
        self._current_bar = 0

    @property
    def is_active(self) -> bool:
        return self._active

    @property
    def is_complete(self) -> bool:
        return self._active and self._current_bar >= self._ramp_bars

    def get_blend_weight(self) -> float:
        """Get current blending weight for shadow model [0, 1]."""
        if not self._active:
            return 0.0
        weight = min(self._current_bar / self._ramp_bars, 1.0)
        return weight

    def step(self) -> float:
        """Advance one bar and return current blend weight."""
        if self._active:
            self._current_bar += 1
        return self.get_blend_weight()

    def blend_actions(self, live_action: float, shadow_action: float) -> float:
        """Blend live and shadow actions based on current rollout progress.

        Args:
            live_action: Current live model's action
            shadow_action: Shadow model's action

        Returns:
            Blended action
        """
        weight = self.get_blend_weight()
        blended = (1.0 - weight) * live_action + weight * shadow_action
        return float(blended)
